### ISSUE TITLE
UI line render - curved lines

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#28]
<sup>Issue created by rahu ketulya as [Bitbucket Issue #&#8203;28](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/28) on 2015.09.29 08:20.</sup>
The UI **LineRenderer** is the fantastic feature to have. It will be more great if some one puts some effort to make the lines possible to smooth and make curved lines.
Thanks in advance to all those who put all these here for the community.
Rahul

**Comment by EpsilonD3lta** [comment]
Bezier curve is quite limited. It would be nice and very useful to extend this feature to b-splines

**Comment by SimonDarksideJ** [comment]
Best to log a new Feature request then @EpsilonD3lta , help appreciated

**Comment by EpsilonD3lta** [comment]
Created feature request 
https://github.com/Unity-UI-Extensions/com.unity.uiextensions/issues/402#issue-1306357341
