### ISSUE TITLE
UI_Knob - Continue dragging outside control aera

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#351]
<sup>Issue created by Jens Hellermann as [Bitbucket Issue #&#8203;351](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/351) on 2020.10.15 10:50.</sup>
It would be good, if dragging could continue outside the control area, for mobile development and small screens. The handling of the knob becomes a bit finicky on a mobile phone.

**Comment by atesija** [comment]
I'm still seeing this as an issue. When my mouse leaves the knob it doesn't continue to update.
Testing:
- Downloaded Version 2.3.2
- Add a UI Knob to the scene
- Run
- Rotate knob by clicking and dragging it

What I see:
I can rotate the knob just fine as long as the mouse is inside the knob but when it leaves it stops rotating. Bringing the mouse back in while I'm holding left click still will snap the knob to the right position.
