### ISSUE TITLE
Last Element in Flow Layout Group Doesn't Use Entire Width

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#357]
<sup>Issue created by Sophie Davis as [Bitbucket Issue #&#8203;357](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/357) on 2020.11.05 01:20.</sup>
The last element in the Flow Layout Group \(Start Axis Horizontal\) that would otherwise use a full or multiple lines doesn’t take up the entire width of the Flow Layout Group. Instead, it stops early to needless leave a Spacing X amount of room from the edge.

‌

**Replication Instructions:**

1. Create a new GameObject with a FlowLayoutGroup component.
2. Set the Spacing X to a significantly high number to be very obviously visible.
3. Create multiple children with Unity’s Text component.
4. Enter enough text in each to ensure they take up multiple lines
5. Observe the last child does not use the correct width.

‌

**Comment by gabrieloc** [comment]
Hello, I'm experiencing an issue which I believe is related.

With two elements in a FlowLayoutGroup, if I select `Child Force Expand Width` and increase `Spacing X`, the last row only will overflow incorrectly. If there is more than one row, all other rows are laid out correctly.

Please let me know if I've misinterpreted how to use this class.
