### ISSUE TITLE
UIParticleSystem: Getting deprecation warning

### ISSUE THREAD

**Issue by eddiecStarArcher** [Unity-UI-Extensions/com.unity.uiextensions#399]
Yesterday, I purchased and installed UI Extensions Version 2019.6 and immediately starting seeing this deprecation warning:

Assets/com.unity.uiextensions/Runtime/Scripts/Effects/UIParticleSystem.cs(229,33): warning CS0618: 'ParticleSystem.TextureSheetAnimationModule.useRandomRow' is obsolete: 'useRandomRow property is deprecated. Use rowMode instead.'

I'm using Unity 2021.3.2f1

Help?

Thank you,
Eddie

**Comment by SimonDarksideJ** [comment]
Thanks for the heads up, will ensure this is updated and handled for the next release

**Comment by SimonDarksideJ** [comment]
Resolved via
https://github.com/Unity-UI-Extensions/com.unity.uiextensions/issues/411
