### ISSUE TITLE
Scroll Snap bool params misunderstanding

### ISSUE THREAD

**Issue by hugoymh** [Unity-UI-Extensions/com.unity.uiextensions#400]
I've found _JumpOnEnable_ and _RestartOnEnable_ a little confusing based on their description written in both the documentation and in code.

_JumpOnEnable_ is false by default but it seems to actually causing the scroll snap to jump directly instead of lerp when its value is false
(i.e. the naming of this variable suggest the opposite behavior instead of what it currently does)

_RestartOnEnable_ behaves as expected as its naming implies, but it is false by default even though the description said it should be true.

**Comment by SimonDarksideJ** [comment]
Sorry for the delay in responding @hugoymh , will be updating the docs today.  Thanks for the clarifications.

**Comment by SimonDarksideJ** [comment]
OK, I updated the documentation for the *RestartOnEnable* property, which you are entirely correct is reversed from the description.

However, the *JumpOnEnable* feature does not seem to actually work, and the container always scrolls.  So I'll fix that.

**Comment by SimonDarksideJ** [comment]
Resolved
