### ISSUE TITLE
undeclared identifier 'sampler_CameraDepthTexture'

### ISSUE THREAD

**Issue by TheReconJacob** [Unity-UI-Extensions/com.unity.uiextensions#401]
I get an error whenever I make an android build. The error is something along the lines of `undeclared identifier 'sampler_CameraDepthTexture'`. This seems to be related to the shaders located in Runtime -> Resources -> Shaders. I was able to temporarily fix it by editing the shaders that contain `sampler2D_float _CameraDepthTexture;` and replace them with `UNITY_DECLARE_DEPTH_TEXTURE(_CameraDepthTexture);`. But unfortunately since they just automatically recreate themselves after a build is finished, the errors return again.

This is a purely cosmetic error and doesn't seem to have any effect on the build when it is made. But it'd be nice to know if there is a way to get rid of the errors to avoid confusion.
Thanks in advance.

**Comment by SimonDarksideJ** [comment]
Thanks for the report, will ensure this is addressed in the next release
