### ISSUE TITLE
UPM Version

### ISSUE THREAD

**Issue by fakegood** [Unity-UI-Extensions/com.unity.uiextensions#407]
Looking through [NPM](https://www.npmjs.com/package/com.unity.uiextensions) cannot find v2.5, it is updated 1 year ago with v2.2.7, can i know how or will I get the latest version through Unity package manager?

**Comment by SimonDarksideJ** [comment]
This will be published to OpenUPM for its next release as well as NPM.

However, the latest release is still 2.2.7 based on the package.json in the repository.   As we upgrade to GitHub, I'll be sure to give this special attention for the 2.3 release.

**Comment by SimonDarksideJ** [comment]
OK, one last task for releasing the 2.3 updates:

* Publish docs to GitHub pages site
* Update all links/references to the new site
* Finalise UPM package reference
* Include GitHub Actions build/verification process
* Find solace in a task almost but never done

**Comment by SimonDarksideJ** [comment]
Package update to OpenUPM done, just awaiting confirmation

**Comment by SimonDarksideJ** [comment]
@fakegood the NPM release is updated btw, just pushed that today :D 2.3 is out.
OpenUPM is pending, which is my preference these days.
