### ISSUE TITLE
Adding Unity UI Extension to a project using HSV Color Picker causes conflict

### ISSUE THREAD

**Issue by jacattrongnlh** [Unity-UI-Extensions/com.unity.uiextensions#408]
How to reproduce:

- Add this package to the project: https://github.com/judah4/HSV-Color-Picker-Unity.
- Add Unity UI Extension (UUE) to the project.

What happens: after importing, UUE will overwrite HSV Color Picker's scripts, causing error.

What I've tried to fix this: I tried not letting UUE's overwrite HSV Color Picker's files, but this leads to further error inside UUE because the latest version of those scripts in HSV Color Picker does not work with UUE.
 
What should happens: I notice UUE has some scripts that are using the same .meta files with HSV Color Picker's script files., this leads to Unity overwrite HSV Color Picker's files because Unity think they are the same files.

Suggested fix: Either:
1. Change the .meta files of the conflict files in UUE so it will not conflict with HSV Color Picker.
2. List HSV Color Picker as a dependency (specify a version that work with UUE) and remove all HSV Color Picker's files from UUE.

**Comment by SimonDarksideJ** [comment]
Thanks for the report, will ensure the meta files for the HSV picker are regenerated for the next release

**Comment by SimonDarksideJ** [comment]
Hard reset the guid's used in the UI Extensions to avoid conflict with those in the original asset.
Although if there are changes, the feature should be updated with source in the future.
