### ISSUE TITLE
UIVerticleScroller - Issue with TextMeshProUGUI Null Reference exception.

### ISSUE THREAD

**Issue by Gohloum** [Unity-UI-Extensions/com.unity.uiextensions#410]
Hello,

I have a spinner component I built with your UIVerticalScroller. In the past it worked fine with TextMeshProUGUI controls. However upon updating the project from 2020 to 2022, and updating the library, I now get an error from line 194:

`result = _arrayOfElements[i].GetComponentInChildren<Text>().text;`

My assumption is at some point TextMeshPro no longer inherits from the Legacy Text and thus a null ref is returned by GetComponentInChildren preventing access to .text property.  

Do you have any suggestions for a workaround or is this something that can be address? 

Full Error: 
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.Extensions.UIVerticalScroller.Update () (at Library/PackageCache/com.unity.uiextensions@9fadad0f72/Runtime/Scripts/Layout/UIVerticalScroller.cs:194)

**Comment by Gohloum** [comment]
Hello, It's been a week. Is there any status on this issue?

**Comment by SimonDarksideJ** [comment]
Hi @Gohloum , for some reason I didn't get a notification for the issue.  I've not come across this issue as yet, but will find some time to look in to it.
But for reference, we have not done testing in 2022 as it's not LTS yet.

**Comment by Gohloum** [comment]
Thanks for getting back to me.  I will hold off on trying a workaround or alternative for now. Just let me know what you find when you have time. I'll stay subscribed to this thread.

**Comment by SimonDarksideJ** [comment]
@Gohloum , the fix is in the 2.3 working branch if you want to copy it
https://github.com/Unity-UI-Extensions/com.unity.uiextensions/blob/feature/V2.3.0/Runtime/Scripts/Layout/UIVerticalScroller.cs

WIll be included with 2.3 when I can get it released.

**Comment by Gohloum** [comment]
Thank you Simon! I will grab this for now until you have the 2.3 release out.  Thank you again for addressing this!
