### ISSUE TITLE
UIParticleSystem not getting disposed properly - Memory Leak

### ISSUE THREAD

**Issue by revolt3r** [Unity-UI-Extensions/com.unity.uiextensions#412]
OnDestroy override is missing base.OnDestroy(); which causes the behaviour to be forever referenced in GraphicRegistry

**Comment by SimonDarksideJ** [comment]
Sneaking in before the big 2.3 update, hmmm.  

Will look at asap.  Should be an easy fix, will also review other implementations are behaving.

Thanks
