### ISSUE TITLE
BUG: Build failure - The type or namespace name 'Extensions' does not exist in the namespace 'UnityEngine.UI' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by aholla** [Unity-UI-Extensions/com.unity.uiextensions#414]
# Unity UI Extensions Bug Report

## Describe the bug
When trying to build with CloudBuild I get this error:

The type or namespace name 'Extensions' does not exist in the namespace 'UnityEngine.UI' (are you missing an assembly reference?)

This is in a script that references the paginationManager.

**Comment by SimonDarksideJ** [comment]
Thanks for the report, will look into it asap

Can you confirm the issue is coming from a UIExtensions class or reported by a local script?  (E.G. have you checked your assembly definition)

**Comment by SimonDarksideJ** [comment]
OK, run through several builds including building on our new GitHub build workflow without issue.

@aholla can you give an example of the script that is raising the errors so we can replicate it?

**Comment by aholla** [comment]
I dont know sorry, i had to remove it and write something custom as im on a
tight deadline.

**Comment by SimonDarksideJ** [comment]
No worries, hopefully, you can come back to it in the future and let us know what the problem was.
Closing for now until it can be replicated.
