### ISSUE TITLE
BUG: FlowLayoutGroup incorrect spacing handling

### ISSUE THREAD

**Issue by mrobaczyk** [Unity-UI-Extensions/com.unity.uiextensions#432]
# Unity UI Extensions Bug Report

## Describe the bug
FlowLayoutGroup does not handle spacing correctly. My setup is:
- child alignment: Upper right
- spacing X: 10

## Actual behaviour
The 2nd item in the 2nd row goes out of the parent. Even if it is in the same line the same bug is present.

See the attached screenshots:

![image](https://user-images.githubusercontent.com/35763893/219076086-48395504-1d47-4db1-9d63-3ff60cac8918.png)

**Comment by SimonDarksideJ** [comment]
Thanks for the report @mrobaczyk , will check it out ASAP

**Comment by gabrieloc** [comment]
Any chance this is related to https://github.com/Unity-UI-Extensions/com.unity.uiextensions/issues/357? (Sorry for the spam, hoping this is on your radar still)

**Comment by SimonDarksideJ** [comment]
That fix resolved an issue where the last item in the flow group did not align correctly, are you saying that fix has also inadvertently caused this issue? 

* Can you try reverting the fix in your project to see if it resolves the problem
* Or provide a sample scene with your setup so I can test?

**Comment by gabrieloc** [comment]
Here's a screenshot of the project demonstrating the issue
<img width="990" alt="Screenshot 2023-03-11 at 11 27 51 AM" src="https://user-images.githubusercontent.com/983669/224495970-e031848f-047b-4ea2-8e5f-746536ce1e8e.png">

You can find it here:
https://drive.google.com/file/d/1_etF0a2OPAMPW8RPzRrgt_CKfAHtzZmF/view?usp=sharing

**Comment by SimonDarksideJ** [comment]
FYI @gabrieloc , when zipping a project, you can ignore the library folder 🤣

**Comment by SimonDarksideJ** [comment]
You should be able to test the fix in the latest preview OpenUPM package (2.3.2-pre.1) or refresh your development link.

Let me know how it goes @gabrieloc

**Comment by gabrieloc** [comment]
> FYI @gabrieloc , when zipping a project, you can ignore the library folder 🤣

Ah yes, I just blindly assumed a fresh Unity project would be over 100mb 😄

I will check out 2.3.2p1, thanks for the super quick response!

**Comment by SimonDarksideJ** [comment]
Happy to help, this one certainly did provide a challenge in resolving, just trying to find why it was not wrapping to the next line when it was overflowing.

And please close this issue if resolved @gabrieloc

**Comment by gabrieloc** [comment]
Sorry to reply 3 months later, I forgot to mention I checked out the development branch of this repo (2.3.2) and it fixes the issue. @mrobaczyk you should check if this resolves your problem as well.

@SimonDarksideJ any plans to release 2.3.2? It seems it's has been sitting around for a little while now 😆

**Comment by SimonDarksideJ** [comment]
I was hoping to get some more in before the 2.3.2 release, granted, finding time is tricky most days.
Are you saying this issue exists in 2.3.0 but not in the current development state @gabrieloc ?

**Comment by gabrieloc** [comment]
Correct, fixed in the development branch.

**Comment by SimonDarksideJ** [comment]
OK, will see if I can carve out some time this weekend to get some updates in and push the 2.3.2 release, which is always a lot of work.

**Comment by gabrieloc** [comment]
Totally understand, appreciate all the great you've done with this project!
