### ISSUE TITLE
BUG: Letter Spacing not working in Unity 2022 with TMP

### ISSUE THREAD

**Issue by andy0x10** [Unity-UI-Extensions/com.unity.uiextensions#433]
# Unity UI Extensions Bug Report

## Describe the bug
I've added Letter Spacing effect component below the Text Mesh Pro - Text UI component but it doesn't seem to do anything.  I'm using the latest 2.3 release of Unity-UI-Extensions and Unity 2022.2.7f1.  I thought the new version supported TMP, and looking at the source it looks like it is designed to.  It seems that ModifyMesh() is never being called.  Have I missed something obvious or is this a bug?

**Comment by SimonDarksideJ** [comment]
Thanks for the report @andy0x10, will check it out ASAP

**Comment by SimonDarksideJ** [comment]
OK, found the problem, TextMeshPro overrides the base vertex handling, so none of the Text Effects in the UI Extensions will work as they all depend on vertex manipulation.
However, TextMeshPro does seem to offer similar effects within its configuration, so I would recommend using those.
