### ISSUE TITLE
BUG: Compile Errors on Package Import

### ISSUE THREAD

**Issue by BAI-PatrickManalich** [Unity-UI-Extensions/com.unity.uiextensions#438]
# Unity UI Extensions Bug Report

## Describe the bug
Hi, thanks for all your great work! I followed https://unity-ui-extensions.github.io/UPMInstallation.html to install this package. Upon import I get the following exceptions:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/42355473/226962182-ed683cff-fb4e-42da-90c5-7ee90e94c35e.png">

## To Reproduce

1. Download Unity editor version 2021.3.3f1
2. Open Package Manager window
3. Click "Add package from git URL" and insert https://github.com/Unity-UI-Extensions/com.unity.uiextensions.git

## Your Setup

- **Operation System:**
    - [X] Windows
    - [ ] MacOs
    - [ ] Linux
    - [ ] Other 
- **Unity Version:** Unity editor version 2021.3.3f1
- **Unity UI Extensions Version**
    - [ ] 2.3.0

**Comment by SimonDarksideJ** [comment]
Hi @BAI-PatrickManalich sorry for the late response (no idea what has happened to my notifications)
Just tested with both the latest pre-release and version 2.3 in a new Unity 2021 project and could not replicate the issue.

Are you still having this issue?

**Comment by BAI-PatrickManalich** [comment]
@SimonDarksideJ I just tested again and now it's working 🤦‍♂️ I'm not sure what changed, but it seemed to be local Unity editor issue. Sorry for the false alarm, thanks for the response! Closing this PR.
