### ISSUE TITLE
Feature Request: Accordion - Dynamic content before Start()/Awake()

### ISSUE THREAD

**Issue by jonathan-bryant** [Unity-UI-Extensions/com.unity.uiextensions#455]
Unity UI Extensions Feature Request - Dynamic content before Start()/Awake()

I was having issues with the Accordion component loading correctly, especially in build.
This was due to dynamic content being added before the first frame. Adding the below to [AccordionElement.cs](https://github.com/Unity-UI-Extensions/com.unity.uiextensions/blob/release/Runtime/Scripts/Controls/Accordion/AccordionElement.cs) fixed it for me:
	
```
private IEnumerator Start()
{
	yield return null; // Wait for the first frame
	OnValueChanged(this.isOn);
}
```

**Comment by jonathan-bryant** [comment]
It's worth noting that a side effect of this issue was the inability to open that element after the first frame without enabling another element.

**Comment by SimonDarksideJ** [comment]
That is a severe limitation for how the Unity UI system works sadly @jonathan-bryant , although I will add an action to look into being able to initialise the control with some input to possible enable this capability.
