### ISSUE TITLE
BUG: Obsolete ScrollPositionController Causes Error in Unity 2023.2.2f1 with UI Extensions 2.3.2

### ISSUE THREAD

**Issue by GID0317** [Unity-UI-Extensions/com.unity.uiextensions#465]
# Unity UI Extensions Bug Report

com.unity.uiextensions\Editor\ScrollPositionControllerEditor.cs(10,26): error CS0619: 'ScrollPositionController' is obsolete: 'ScrollPositionController has been replaced by the Scroller component'

- **Operation System:**
    - [x] Windows 

- **Unity Version:** 2023.2.2f1
- **Unity UI Extensions Version**
    - [x] 2.3.2

## Additional context
There are some breaking changes in the future Unity 2023.2.2f1 that require some of the code inside ScrollPositionControllerEditor.cs to be updated. In this case, ‘ScrollPositionController’ needs to be replaced by the ‘Scroller’ component.

**Comment by SimonDarksideJ** [comment]
This is expected behaviour in the recent 2.3.2 update, mainly to denote changes made in 2023.  They are just advisory atm to help developers migrate if they want to.  But are not mandatory.  The current 2.3.2 release was tested with 2023.2.1f1.
Hope that helps.
