### ISSUE TITLE
Could not be found....   "com.unity.uiextensions": "2.3.2",

### ISSUE THREAD

**Issue by XeonG** [Unity-UI-Extensions/com.unity.uiextensions#467]
Could not be found... is this properly updated for upm stuff?

**Comment by SimonDarksideJ** [comment]
Sorry for the delay in responding, can you elaborate on the issue please @XeonG ?

Replication instructions?

**Comment by XeonG** [comment]
I just switched to using this via the git url instead... this is on upm https://openupm.com/packages/com.unity.uiextensions/   tis outdated and broken or something like that..

**Comment by SimonDarksideJ** [comment]
OK, just checked and installed the package from OpenUPM @XeonG and did not have any issues.

Unity seems to have added a new "feature" to the Package manager to "warn" about packages (likely to discourage from using non-unity ones), but it has no effect.

Loaded the samples and everything compiles and works as far as I can see.

Is there some specific issue that you are facing using the OpenUPM version?

Using the OpenUPM cli, I used the following command
```text
openupm add com.unity.uiextensions
```

Which alongside adding the package, added the following custom scope
![image](https://github.com/Unity-UI-Extensions/com.unity.uiextensions/assets/1793042/9e402afc-e017-4980-adf1-ba30ce9385fc)

**Comment by XeonG** [comment]
yeah I guess that must have been it.. I just thought it was broken
